# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  unifi_api_key: '{{ env.UNIFI_API_KEY }}'
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: 'Unifi Site Manager'
    }
  }
