---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: |
  https://api.ui.com/v1/sites
  https://api.ui.com/v1/hosts
  https://api.ui.com/v1/devices
polling_headers: x-api-key={{ unifi_api_key }}
id: 102852
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Shows the status of your connected Ubiquiti Unifi Sites.
  github_url: https://github.com/stephenyeargin/trmnl-unifi-site-manager
  learn_more_url: https://ui.com/how-it-works
  email_address: stephen@yearg.in
- keyname: unifi_api_key
  field_type: password
  name: API Key
  description: Unifi Site Manager API Key, see <a href="https://developer.ui.com/site-manager-api/" class="underline">documentation</a> for details.
  placeholder: xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
- keyname: unifi_site_id
  field_type: string
  name: Site ID
  description: The UUID of a particular site you want displayed on the dashboard. Only available via REST API call.
  placeholder: xxxxxxxxxxxxxxxxxxxxxxxx
name: Unifi Site Manager
refresh_interval: 15
